install:
	npm install

dev:
	npm run start:dev

build:
	npm run build

lint:
	npm run lint

format:
	npm run format

prisma-generate:
	npm run prisma:generate

prisma-migrate:
	npm run prisma:migrate:dev

docker-up:
	docker compose up -d postgres redis

docker-down:
	docker compose down

docker-up-full:
	docker compose up -d --build
