import type { CivilizationStateRecord } from './repositories';

export function serializeCivilizationSnapshot(
  state: CivilizationStateRecord,
): Record<string, unknown> {
  return {
    game: {
      id: state.id,
      name: state.name,
      status: state.status,
      startAt: state.startAt.toISOString(),
      endAt: state.endAt.toISOString(),
      completedAt: state.completedAt?.toISOString() ?? null,
      winnerTeamId: state.winnerTeamId,
      completionReason: state.completionReason,
      settings: state.settingsJson,
      stateVersion: state.stateVersion,
      createdAt: state.createdAt.toISOString(),
      updatedAt: state.updatedAt.toISOString(),
    },
    teams: state.teams.map((team) => ({
      id: team.id,
      side: team.side,
      name: team.name,
      color: team.color,
      visualKey: team.visualIdentifier,
      townHallTileId: team.townHallTileId,
      finalScore: team.finalScore?.toString() ?? null,
      createdAt: team.createdAt.toISOString(),
    })),
    tiles: state.tiles.map((tile) => ({
      id: tile.id,
      q: tile.q,
      r: tile.r,
      terrainType: tile.terrainType,
      ownerTeamId: tile.ownerTeamId,
      isConnected: tile.isConnected,
      createdAt: tile.createdAt.toISOString(),
      updatedAt: tile.updatedAt.toISOString(),
    })),
    spawnPoints: state.spawnPoints.map((spawn) => ({
      id: spawn.id,
      teamId: spawn.teamId,
      tileId: spawn.tileId,
      createdAt: spawn.createdAt.toISOString(),
    })),
    buildings: state.buildings.map((building) => ({
      id: building.id,
      tileId: building.tileId,
      type: building.buildingType,
      attributeKey: building.attributeKey,
      ownerTeamId: building.ownerTeamId,
      captureTeamId: building.captureTeamId,
      captureProgressUnits: building.captureProgressUnits,
      captureRequiredUnits: building.captureRequiredUnits,
      incomePerHour: building.incomePerHour.toString(),
      status: building.status,
      createdAt: building.createdAt.toISOString(),
      updatedAt: building.updatedAt.toISOString(),
    })),
    towers: state.towers.map((tower) => ({
      id: tower.id,
      tileId: tower.tileId,
      teamId: tower.teamId,
      status: tower.status,
      workKind: tower.workKind,
      protectionRadius: tower.protectionRadius,
      destructionProgressActions: tower.destructionProgressActions,
      destructionRequiredActions: tower.destructionRequiredActions,
      constructionStartedAt: tower.constructionStartedAt.toISOString(),
      constructionCompletesAt: tower.constructionCompletesAt?.toISOString() ?? null,
      destroyedAt: tower.destroyedAt?.toISOString() ?? null,
      createdByPlayerId: tower.createdByPlayerId,
      createdAt: tower.createdAt.toISOString(),
      updatedAt: tower.updatedAt.toISOString(),
    })),
    players: state.players.map((player) => ({
      id: player.id,
      userId: player.userId,
      username: player.user.username,
      avatarUrl: player.user.avatarUrl,
      teamId: player.teamId,
      initialTileId: player.initialTileId,
      currentTileId: player.currentTileId,
      spawnTileId: player.spawnTileId,
      actionPointUnits: player.actionPointUnits,
      lastActionPointUpdateAt: player.lastActionPointUpdateAt.toISOString(),
      joinedAt: player.joinedAt.toISOString(),
      isActive: player.isActive,
      createdAt: player.createdAt.toISOString(),
      updatedAt: player.updatedAt.toISOString(),
    })),
    teamResources: state.teamResources.map((resource) => ({
      teamId: resource.teamId,
      goldAmount: resource.goldAmount.toString(),
      goldIncomePerHour: resource.goldIncomePerHour.toString(),
      lastSettledAt: resource.lastSettledAt.toISOString(),
      updatedAt: resource.updatedAt.toISOString(),
    })),
    attributeResources: state.attributeResources.map((resource) => ({
      teamId: resource.teamId,
      attributeKey: resource.attributeKey,
      amount: resource.amount.toString(),
      incomePerHour: resource.incomePerHour.toString(),
      lastSettledAt: resource.lastSettledAt.toISOString(),
      updatedAt: resource.updatedAt.toISOString(),
    })),
  };
}
