import { HttpException, HttpStatus } from '@nestjs/common';

export const CIVILIZATION_ERROR_CODES = {
  ACTION_ALREADY_PROCESSED: 'ACTION_ALREADY_PROCESSED',
  BUILDING_NOT_CAPTURABLE: 'BUILDING_NOT_CAPTURABLE',
  GAME_ALREADY_ACTIVE: 'GAME_ALREADY_ACTIVE',
  GAME_DATE_OVERLAP: 'GAME_DATE_OVERLAP',
  GAME_IMMUTABLE: 'GAME_IMMUTABLE',
  GAME_NOT_ACTIVE: 'GAME_NOT_ACTIVE',
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',
  INVALID_GAME_CONFIGURATION: 'INVALID_GAME_CONFIGURATION',
  INVALID_IDEMPOTENCY_KEY: 'INVALID_IDEMPOTENCY_KEY',
  INVALID_PLAYER_TARGET: 'INVALID_PLAYER_TARGET',
  NOT_ENOUGH_ACTION_POINTS: 'NOT_ENOUGH_ACTION_POINTS',
  NOT_ENOUGH_TEAM_GOLD: 'NOT_ENOUGH_TEAM_GOLD',
  PLAYER_NOT_ASSIGNED: 'PLAYER_NOT_ASSIGNED',
  SPECTATOR_READ_ONLY: 'SPECTATOR_READ_ONLY',
  TILE_IMPASSABLE: 'TILE_IMPASSABLE',
  TILE_NOT_ADJACENT: 'TILE_NOT_ADJACENT',
  TILE_NOT_FOUND: 'TILE_NOT_FOUND',
  TILE_OCCUPIED_BY_ENEMY: 'TILE_OCCUPIED_BY_ENEMY',
  TILE_PROTECTED_BY_TOWER: 'TILE_PROTECTED_BY_TOWER',
  TOO_MANY_ACTIONS: 'TOO_MANY_ACTIONS',
  TOWER_NOT_ATTACKABLE: 'TOWER_NOT_ATTACKABLE',
  TOWER_NOT_REPAIRABLE: 'TOWER_NOT_REPAIRABLE',
  TOWER_PLACEMENT_INVALID: 'TOWER_PLACEMENT_INVALID',
  TOWER_RADIUS_OVERLAP: 'TOWER_RADIUS_OVERLAP',
  TOWN_HALL_PROTECTED: 'TOWN_HALL_PROTECTED',
} as const;

export type CivilizationErrorCode =
  (typeof CIVILIZATION_ERROR_CODES)[keyof typeof CIVILIZATION_ERROR_CODES];

export class CivilizationException extends HttpException {
  constructor(
    code: CivilizationErrorCode,
    message: string,
    status: HttpStatus = HttpStatus.CONFLICT,
    details?: unknown,
  ) {
    super(
      {
        code,
        message,
        ...(details === undefined ? {} : { details }),
      },
      status,
    );
  }
}
