CREATE TYPE "BossBattleStatus" AS ENUM ('DRAFT','SCHEDULED','ACTIVE','DEFEATED','EXPIRED','CANCELLED','FINALIZING','COMPLETED');
CREATE TYPE "BossRewardClaimStatus" AS ENUM ('NOT_ELIGIBLE','AVAILABLE','PROCESSING','CLAIMED','FAILED');

CREATE TABLE "boss_battles" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"description" TEXT,"image_url" TEXT,"starts_at" TIMESTAMP(3) NOT NULL,"ends_at" TIMESTAMP(3) NOT NULL,"initial_hp" INTEGER NOT NULL,"current_hp" INTEGER NOT NULL,"total_applied_damage" INTEGER NOT NULL DEFAULT 0,"strength" INTEGER NOT NULL,"charisma" INTEGER NOT NULL,"endurance" INTEGER NOT NULL,"intelligence" INTEGER NOT NULL,"attack_cooldown_seconds" INTEGER NOT NULL,"status" "BossBattleStatus" NOT NULL DEFAULT 'DRAFT',"defeated_at" TIMESTAMP(3),"finished_at" TIMESTAMP(3),"results_finalized_at" TIMESTAMP(3),"version" INTEGER NOT NULL DEFAULT 1,"rewards_enabled" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "boss_battle_hp_check" CHECK (initial_hp > 0 AND current_hp >= 0 AND current_hp <= initial_hp),CONSTRAINT "boss_battle_period_check" CHECK (starts_at < ends_at),CONSTRAINT "boss_battle_cooldown_check" CHECK (attack_cooldown_seconds > 0));
CREATE TABLE "boss_battle_rewards" ("id" TEXT PRIMARY KEY,"boss_battle_id" TEXT NOT NULL,"place_from" INTEGER NOT NULL,"place_to" INTEGER NOT NULL,"gold_amount" INTEGER NOT NULL DEFAULT 0,"game_score_amount" INTEGER NOT NULL DEFAULT 0,"strength" INTEGER NOT NULL DEFAULT 0,"charisma" INTEGER NOT NULL DEFAULT 0,"endurance" INTEGER NOT NULL DEFAULT 0,"intelligence" INTEGER NOT NULL DEFAULT 0,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "boss_reward_places_check" CHECK (place_from >= 1 AND place_to >= place_from),CONSTRAINT "boss_reward_component_check" CHECK (gold_amount > 0 OR game_score_amount > 0 OR strength > 0 OR charisma > 0 OR endurance > 0 OR intelligence > 0));
CREATE TABLE "boss_reward_item_templates" ("id" TEXT PRIMARY KEY,"boss_battle_reward_id" TEXT NOT NULL UNIQUE,"name" TEXT NOT NULL,"description" TEXT,"image_url" TEXT,"slot_type" "EquipmentSlotType" NOT NULL,"rarity" "ItemRarity" NOT NULL,"durability" INTEGER,"strength" INTEGER,"charisma" INTEGER,"agility" INTEGER,"intelligence" INTEGER,"metadata" JSONB,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "boss_battle_rewards" DROP CONSTRAINT "boss_reward_component_check";
CREATE TABLE "boss_attacks" ("id" TEXT PRIMARY KEY,"boss_battle_id" TEXT NOT NULL,"user_id" TEXT NOT NULL,"calculated_damage" INTEGER NOT NULL,"applied_damage" INTEGER NOT NULL,"user_power" DOUBLE PRECISION NOT NULL,"boss_power" DOUBLE PRECISION NOT NULL,"random_multiplier" DOUBLE PRECISION NOT NULL,"user_attributes_snapshot" JSONB NOT NULL,"boss_attributes_snapshot" JSONB NOT NULL,"formula_identifier" TEXT NOT NULL,"formula_version" INTEGER NOT NULL,"attacked_at" TIMESTAMP(3) NOT NULL,"cooldown_slot" TIMESTAMP(3) NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "boss_attack_damage_check" CHECK (calculated_damage >= 0 AND applied_damage >= 0 AND applied_damage <= calculated_damage),CONSTRAINT "boss_attack_random_check" CHECK (random_multiplier >= 0.9 AND random_multiplier <= 1.1),UNIQUE("boss_battle_id","user_id","cooldown_slot"));
CREATE TABLE "boss_battle_participants" ("id" TEXT PRIMARY KEY,"boss_battle_id" TEXT NOT NULL,"user_id" TEXT NOT NULL,"total_damage" INTEGER NOT NULL DEFAULT 0,"attacks_count" INTEGER NOT NULL DEFAULT 0,"first_attack_at" TIMESTAMP(3) NOT NULL,"last_attack_at" TIMESTAMP(3) NOT NULL,"last_cooldown_slot" TIMESTAMP(3) NOT NULL,"next_attack_at" TIMESTAMP(3) NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,UNIQUE("boss_battle_id","user_id"));
CREATE TABLE "boss_battle_results" ("id" TEXT PRIMARY KEY,"boss_battle_id" TEXT NOT NULL,"user_id" TEXT NOT NULL,"place" INTEGER NOT NULL,"total_damage" INTEGER NOT NULL,"attacks_count" INTEGER NOT NULL,"first_attack_at" TIMESTAMP(3) NOT NULL,"last_attack_at" TIMESTAMP(3) NOT NULL,"reward_id" TEXT,"reward_claim_status" "BossRewardClaimStatus" NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,UNIQUE("boss_battle_id","user_id"));
CREATE TABLE "boss_reward_claims" ("id" TEXT PRIMARY KEY,"boss_battle_id" TEXT NOT NULL,"boss_battle_result_id" TEXT NOT NULL UNIQUE,"boss_battle_reward_id" TEXT NOT NULL,"user_id" TEXT NOT NULL,"place" INTEGER NOT NULL,"status" "BossRewardClaimStatus" NOT NULL,"idempotency_key" TEXT NOT NULL,"reward_snapshot" JSONB NOT NULL,"attempt_count" INTEGER NOT NULL DEFAULT 1,"last_error" TEXT,"claimed_at" TIMESTAMP(3),"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,UNIQUE("boss_battle_id","user_id"));
CREATE TABLE "boss_battle_audit_logs" ("id" TEXT PRIMARY KEY,"boss_battle_id" TEXT NOT NULL,"admin_user_id" TEXT NOT NULL,"action" TEXT NOT NULL,"before_data" JSONB,"after_data" JSONB,"reason" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE INDEX ON "boss_battles"("status","starts_at"); CREATE INDEX ON "boss_battles"("status","ends_at");
CREATE INDEX ON "boss_battle_rewards"("boss_battle_id","place_from","place_to");
CREATE INDEX ON "boss_attacks"("boss_battle_id","attacked_at"); CREATE INDEX ON "boss_attacks"("boss_battle_id","user_id","attacked_at" DESC);
CREATE INDEX ON "boss_battle_participants"("boss_battle_id","total_damage" DESC);
CREATE INDEX ON "boss_battle_results"("boss_battle_id","place"); CREATE INDEX ON "boss_battle_results"("user_id","created_at" DESC);
CREATE INDEX ON "boss_reward_claims"("user_id","status"); CREATE INDEX ON "boss_reward_claims"("boss_battle_id","status");
CREATE INDEX ON "boss_battle_audit_logs"("boss_battle_id","created_at" DESC);

ALTER TABLE "boss_battle_rewards" ADD FOREIGN KEY ("boss_battle_id") REFERENCES "boss_battles"("id") ON DELETE CASCADE;
ALTER TABLE "boss_reward_item_templates" ADD FOREIGN KEY ("boss_battle_reward_id") REFERENCES "boss_battle_rewards"("id") ON DELETE CASCADE;
ALTER TABLE "boss_attacks" ADD FOREIGN KEY ("boss_battle_id") REFERENCES "boss_battles"("id") ON DELETE RESTRICT; ALTER TABLE "boss_attacks" ADD FOREIGN KEY ("user_id") REFERENCES "Account"("id") ON DELETE RESTRICT;
ALTER TABLE "boss_battle_participants" ADD FOREIGN KEY ("boss_battle_id") REFERENCES "boss_battles"("id") ON DELETE RESTRICT; ALTER TABLE "boss_battle_participants" ADD FOREIGN KEY ("user_id") REFERENCES "Account"("id") ON DELETE RESTRICT;
ALTER TABLE "boss_battle_results" ADD FOREIGN KEY ("boss_battle_id") REFERENCES "boss_battles"("id") ON DELETE RESTRICT; ALTER TABLE "boss_battle_results" ADD FOREIGN KEY ("user_id") REFERENCES "Account"("id") ON DELETE RESTRICT; ALTER TABLE "boss_battle_results" ADD FOREIGN KEY ("reward_id") REFERENCES "boss_battle_rewards"("id") ON DELETE RESTRICT;
ALTER TABLE "boss_reward_claims" ADD FOREIGN KEY ("boss_battle_id") REFERENCES "boss_battles"("id") ON DELETE RESTRICT; ALTER TABLE "boss_reward_claims" ADD FOREIGN KEY ("boss_battle_result_id") REFERENCES "boss_battle_results"("id") ON DELETE RESTRICT; ALTER TABLE "boss_reward_claims" ADD FOREIGN KEY ("boss_battle_reward_id") REFERENCES "boss_battle_rewards"("id") ON DELETE RESTRICT; ALTER TABLE "boss_reward_claims" ADD FOREIGN KEY ("user_id") REFERENCES "Account"("id") ON DELETE RESTRICT;
ALTER TABLE "boss_battle_audit_logs" ADD FOREIGN KEY ("boss_battle_id") REFERENCES "boss_battles"("id") ON DELETE RESTRICT;
