"use client";
import { PlusIcon, RefreshCwIcon, SearchIcon } from "lucide-react";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { useAdminBossBattlesQuery } from "../api";
import type { BossBattleStatus } from "../model/types";
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/shared/ui/8bit";
const statuses: Array<BossBattleStatus | "ALL"> = ["ALL", "DRAFT", "SCHEDULED", "ACTIVE", "DEFEATED", "FINALIZING", "EXPIRED", "CANCELLED", "COMPLETED"];
const badge: Record<BossBattleStatus,string> = { DRAFT:"bg-slate-500", SCHEDULED:"bg-blue-500", ACTIVE:"bg-emerald-600", DEFEATED:"bg-violet-600", FINALIZING:"bg-amber-600", EXPIRED:"bg-orange-600", CANCELLED:"bg-red-600", COMPLETED:"bg-cyan-700" };
const fmt = (v:string) => new Date(v).toLocaleString();
export function BossBattlesTable() { const router=useRouter(); const query=useAdminBossBattlesQuery(); const [search,setSearch]=useState(""); const [status,setStatus]=useState<BossBattleStatus|"ALL">("ALL"); const [sort,setSort]=useState<"updated"|"name"|"start">("updated"); const [page,setPage]=useState(1); const limit=10;
 const rows=useMemo(()=>[...(query.data??[])].filter(x=>x.name.toLowerCase().includes(search.toLowerCase())&&(status==="ALL"||x.status===status)).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):new Date(sort==="start"?b.startsAt:b.updatedAt).getTime()-new Date(sort==="start"?a.startsAt:a.updatedAt).getTime()),[query.data,search,status,sort]); const pages=Math.max(1,Math.ceil(rows.length/limit)); const shown=rows.slice((page-1)*limit,page*limit);
 return <section className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-semibold">Boss Battles</h1><p className="text-sm text-muted-foreground">Manage bosses, battle windows, and rewards.</p></div><Button onClick={()=>router.push("/admin/boss-battles/create")}><PlusIcon className="size-4"/>Create Boss Battle</Button></div>
 <div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><SearchIcon className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" placeholder="Search by boss name" value={search} onChange={x=>{setSearch(x.target.value);setPage(1)}}/></div><select className="h-9 rounded-md border bg-transparent px-3" value={status} onChange={x=>{setStatus(x.target.value as typeof status);setPage(1)}}>{statuses.map(x=><option key={x}>{x}</option>)}</select><select className="h-9 rounded-md border bg-transparent px-3" value={sort} onChange={x=>setSort(x.target.value as typeof sort)}><option value="updated">Last updated</option><option value="start">Start date</option><option value="name">Boss name</option></select><Button variant="outline" onClick={()=>query.refetch()} disabled={query.isFetching}><RefreshCwIcon className="size-4"/>Refresh</Button></div>
 <Card><CardHeader><CardTitle>Boss Battles</CardTitle><CardDescription>{query.isPending?"Loading...":`${rows.length} battles found`}</CardDescription></CardHeader><CardContent className="space-y-4"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Boss</TableHead><TableHead>Status</TableHead><TableHead>HP</TableHead><TableHead>Damage</TableHead><TableHead>Starts</TableHead><TableHead>Ends</TableHead><TableHead>Cooldown</TableHead><TableHead>Participants</TableHead><TableHead>Updated</TableHead></TableRow></TableHeader><TableBody>{query.isPending?<TableRow><TableCell colSpan={9} className="text-center">Loading boss battles...</TableCell></TableRow>:query.isError?<TableRow><TableCell colSpan={9} className="text-center text-destructive">{query.error.message}</TableCell></TableRow>:shown.length===0?<TableRow><TableCell colSpan={9} className="text-center text-muted-foreground">No boss battles found.</TableCell></TableRow>:shown.map(x=><TableRow key={x.id} className="cursor-pointer" onClick={()=>router.push(`/admin/boss-battles/${x.id}`)}><TableCell className="font-medium">{x.name}</TableCell><TableCell><span className={`rounded-full px-2 py-1 text-xs text-white ${badge[x.status]}`}>{x.status}</span></TableCell><TableCell>{x.currentHp} / {x.initialHp}</TableCell><TableCell>{x.totalAppliedDamage}</TableCell><TableCell>{fmt(x.startsAt)}</TableCell><TableCell>{fmt(x.endsAt)}</TableCell><TableCell>{x.attackCooldownSeconds}s</TableCell><TableCell>{x.participants?.length??"—"}</TableCell><TableCell>{fmt(x.updatedAt)}</TableCell></TableRow>)}</TableBody></Table></div><div className="flex items-center justify-end gap-3"><span className="text-sm text-muted-foreground">Page {page} of {pages}</span><Button size="sm" variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</Button><Button size="sm" variant="outline" disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Next</Button></div></CardContent></Card></section> }
